# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(377, 231)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.title_label.setObjectName("title_label")
        self.year_label = QtWidgets.QLabel(self.centralwidget)
        self.year_label.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.year_label.setObjectName("year_label")
        self.genre_label = QtWidgets.QLabel(self.centralwidget)
        self.genre_label.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.genre_label.setObjectName("genre_label")
        self.duration_label = QtWidgets.QLabel(self.centralwidget)
        self.duration_label.setGeometry(QtCore.QRect(10, 100, 131, 16))
        self.duration_label.setObjectName("duration_label")
        self.title_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.title_edit.setGeometry(QtCore.QRect(140, 10, 221, 21))
        self.title_edit.setObjectName("title_edit")
        self.taste_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.taste_edit.setGeometry(QtCore.QRect(140, 100, 221, 21))
        self.taste_edit.setObjectName("taste_edit")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(240, 190, 121, 31))
        self.add_btn.setObjectName("add_btn")
        self.degree_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.degree_edit.setGeometry(QtCore.QRect(140, 40, 221, 21))
        self.degree_edit.setObjectName("degree_edit")
        self.duration_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.duration_label_2.setGeometry(QtCore.QRect(10, 130, 131, 16))
        self.duration_label_2.setObjectName("duration_label_2")
        self.duration_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.duration_label_3.setGeometry(QtCore.QRect(10, 160, 131, 16))
        self.duration_label_3.setObjectName("duration_label_3")
        self.price_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.price_edit.setGeometry(QtCore.QRect(140, 130, 221, 21))
        self.price_edit.setObjectName("price_edit")
        self.size_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.size_edit.setGeometry(QtCore.QRect(140, 160, 221, 21))
        self.size_edit.setObjectName("size_edit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 70, 221, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить элемент"))
        self.title_label.setText(_translate("MainWindow", "Название"))
        self.year_label.setText(_translate("MainWindow", "Степень обжарки"))
        self.genre_label.setText(_translate("MainWindow", "Зерновой/растворимый"))
        self.duration_label.setText(_translate("MainWindow", "Вкус"))
        self.add_btn.setText(_translate("MainWindow", "Сохранить"))
        self.duration_label_2.setText(_translate("MainWindow", "Цена"))
        self.duration_label_3.setText(_translate("MainWindow", "Объем упаковки"))
